openapi: 3.0.4
info:
  title: A record
  description: creating docu of wapi a record documentation
  version: "2.10"

servers:
  - url: https://172.28.82.7/wapi/v2.10.3
    description: infoblox wapi server

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:

    objectref:
      name: obj_ref
      in: path
      required: true
      schema: 
         type: string
         description: reference to the object

    ReturnFields:
      name: _return_fields
      in: query
      description: Comma-separated fields to return (e.g., name, ipv4addr)
      required: false
      schema:
        type: string
        example: name,ipv4addr

    MaxResults:
      name: _max_results
      in: query
      description: Give positive value to indicate records to be truncated
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 1000

    ReturnFieldsPlus:
      name: _return_fields+
      in: query
      description: Returns basic fields as default as well as non-basic fields when mentioned explicitly
      required: false
      schema:
        type: string
        example: comments

    ReturnAsObject:
      name: _return_as_object
      in: query
      description: If set to 1, returns result as object
      required: false
      schema:
        type: integer
        enum: [0, 1]

    Method:
      name: _method
      in: query
      description: it can be used to override a methods property
      required : false
      schema: 
        type: string
        enum: ["GET","POST","PUT","DELETE"]
    
  schemas:

       ExtensibleAttributes:
        type: object
        additionalProperties:
          type: object
          properties:
            value:
              type: string

       IPv4Addr:
        oneOf:
        - type: string
          description: |
            Provide either a:
            - **Plain IP address** like `"1.2.3.4"`
            - Or a **Next Available IP function string** like:
              - `"func:nextavailableip:network_view=xyz,jisjc"`
              - `"func:nextavailableip:{ffghv}"`
              - `"func:nextavailableip:10.0.0.3-10.0.0.10"`
          example: "func:nextavailableip:10.0.0.0/8"
        - type: object
          description: |
            Or provide an **object for next_available_ip** with more control.

            Example:
            ```json
            {
              "_object_function": "next_available_ip",
              "_parameters": {
                "exclude": ["9.0.0.1", "9.0.0.2"],
                "num": 3
              },
              "_result_field": "ips",
              "_object": "network",
              "_object_parameters": {
                "network": "9.0.0.0/8",
                "network_view": "default"
              }
            }
            ```
          properties:
            _object_function:
              type: string
              example: next_available_ip
            _parameters:
              type: object
              properties:
                exclude:
                  type: array
                  items:
                    type: string
                  example: ["9.0.0.1", "9.0.0.2"]
                num:
                  type: integer
                  example: 3
            _result_field:
              type: string
              example: ips
            _object:
              type: string
              example: network
            _object_parameters:
              type: object
              additionalProperties:
                type: string
                
          required:
            - _object_function
            - _parameters
            - _result_field
            - _object
            - _object_parameters
          example:
            _object_function: next_available_ip
            _parameters:
              exclude: ["9.0.0.1", "9.0.0.2"]
              num: 3
            _result_field: ips
            _object: network
            _object_parameters:
              network: 9.0.0.0/8
              network_view: default

       RecordACreateRequest:
        type: object
        properties:
          name:
            type: string
            writeOnly: True
          ipv4addr: 
            $ref: "#/components/schemas/IPv4Addr"
            writeOnly: True
          ddns_principal:
            type: boolean
            writeOnly: True
          ddns_protected:
            type: boolean
            writeOnly: True
          comment:
            type: string
            writeOnly: True
          creation_time:
            type: string
            format: date-time
            readOnly: True
          creator:
            type: string
            writeOnly: True
          disable:
            type: boolean
            writeOnly: True
          zone:
            type: string
            readOnly: True
          view:
            type: string
            writeOnly: True
          ttl:
            type: integer
            minimum: 0
            maximum: 100
            writeOnly: True
          use_ttl:
            type: boolean
            writeOnly: True
          cloud_info:
            type: object
            readOnly: True
            properties:
              authority_type:
                type: string
                enum: [CP, GM, NONE]
              delegated_member:
                type: object
                properties: 
                  ipv4addr:
                    type: string
                  ipv6addr:
                    type: string
                  name:
                    type: string
              delegated_root:
                type: string
              delegated_scope:
                type: string
                enum: [NONE, RECLAIMING, ROOT, SUBTREE]
              mgmt_platform:
                type: string
              owned_by_adaptor:
                type: boolean
              tenant:
                type: string
              usage:
                type: string
                enum: [ADAPTER, DELEGATED, NONE, USED_BY]

          extattrs:
              $ref: '#/components/schemas/ExtensibleAttributes'
              writeOnly: True


security:
  - basicAuth: []

paths:
  /record:a:
    get:
      summary: Get A Records
      parameters:
        - $ref: '#/components/parameters/ReturnFields'
        - $ref: '#/components/parameters/MaxResults'
        - $ref: '#/components/parameters/ReturnFieldsPlus'
        - $ref: '#/components/parameters/ReturnAsObject'
        - name: filter
          in: query
          required: false
          description: "Dynamic filter parameters (e.g., comment~, name=, status[])."
          schema:
            type: object
            additionalProperties:
              type: string
          style: form
          explode: true
      responses:
        '200':
          description: Successful
        '404':
          description: Referenced object not found
    post: 
      parameters:
      - $ref: '#/components/parameters/Method'
      description: method to create record a
      summary: to create  record
      requestBody: 
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/RecordACreateRequest'
      responses: 
         "200":
            description: hello

  /record:a/{obj_ref}:
     parameters: 
        - $ref: '#/components/parameters/objectref'
     get: 
      description: hi
      summary: hello
      parameters:
        - $ref: '#/components/parameters/ReturnFields'
        - $ref: '#/components/parameters/MaxResults'
        - $ref: '#/components/parameters/ReturnFieldsPlus'
        - $ref: '#/components/parameters/ReturnAsObject'
      responses:
        '200':
          description: Successful
        '404':
          description: Referenced object not found
     post:
      description: hello
      summary: king
      parameters: 
        - $ref: '#/components/parameters/ReturnFields'
        - $ref: '#/components/parameters/Method'
      requestBody: 
        content: 
          application/json:
              schema: 
                $ref: '#/components/schemas/RecordACreateRequest'
      responses: 
        "200":
           description: good
     put:
      description: hello
      summary: king
      parameters: 
          - $ref: '#/components/parameters/ReturnFields' 
      requestBody: 
        content: 
          application/json:
              schema: 
                $ref: '#/components/schemas/RecordACreateRequest'
      responses: 
        "200":
           description: good
     delete:
      description: delete
      summary: king      
      responses: 
        "200":
           description: good
  /request:
     post:
      summary: Execute a series of network management requests
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  method:
                    type: string
                    enum: [GET, POST]
                    description: The HTTP method to use for the request
                  object:
                    type: string
                    description: The object type to interact with
                  data:
                    type: object
                    description: Data to be sent with the request (for GET requests)
                    properties:
                      network:
                        type: string
                        example: 192.168.1.0/24
                  assign_state:
                    type: object
                    description: State assignment for the response
                    properties:
                      netw_ref:
                        type: string
                        example: _ref
                  discard:
                    type: boolean
                    description: Whether to discard the response
                  args:
                    type: object
                    description: Arguments for the POST request
                    properties:
                      _function:
                        type: string
                        example: next_available_ip
                  enable_substitution:
                    type: boolean
                    description: Whether to enable substitution in the request
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  netw_ref:
                    type: string
                    description: Reference to the network object
                  next_available_ip:
                    type: string
                    description: The next available IP address in the network

      
       