/*
A record

creating docu of wapi a record documentation

API version: 2.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RequestPostRequestInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestPostRequestInner{}

// RequestPostRequestInner struct for RequestPostRequestInner
type RequestPostRequestInner struct {
	// The HTTP method to use for the request
	Method *string `json:"method,omitempty"`
	// The object type to interact with
	Object *string `json:"object,omitempty"`
	Data *RequestPostRequestInnerData `json:"data,omitempty"`
	AssignState *RequestPostRequestInnerAssignState `json:"assign_state,omitempty"`
	// Whether to discard the response
	Discard *bool `json:"discard,omitempty"`
	Args *RequestPostRequestInnerArgs `json:"args,omitempty"`
	// Whether to enable substitution in the request
	EnableSubstitution *bool `json:"enable_substitution,omitempty"`
}

// NewRequestPostRequestInner instantiates a new RequestPostRequestInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestPostRequestInner() *RequestPostRequestInner {
	this := RequestPostRequestInner{}
	return &this
}

// NewRequestPostRequestInnerWithDefaults instantiates a new RequestPostRequestInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestPostRequestInnerWithDefaults() *RequestPostRequestInner {
	this := RequestPostRequestInner{}
	return &this
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *RequestPostRequestInner) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInner) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *RequestPostRequestInner) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *RequestPostRequestInner) SetMethod(v string) {
	o.Method = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *RequestPostRequestInner) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInner) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *RequestPostRequestInner) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *RequestPostRequestInner) SetObject(v string) {
	o.Object = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RequestPostRequestInner) GetData() RequestPostRequestInnerData {
	if o == nil || IsNil(o.Data) {
		var ret RequestPostRequestInnerData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInner) GetDataOk() (*RequestPostRequestInnerData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RequestPostRequestInner) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given RequestPostRequestInnerData and assigns it to the Data field.
func (o *RequestPostRequestInner) SetData(v RequestPostRequestInnerData) {
	o.Data = &v
}

// GetAssignState returns the AssignState field value if set, zero value otherwise.
func (o *RequestPostRequestInner) GetAssignState() RequestPostRequestInnerAssignState {
	if o == nil || IsNil(o.AssignState) {
		var ret RequestPostRequestInnerAssignState
		return ret
	}
	return *o.AssignState
}

// GetAssignStateOk returns a tuple with the AssignState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInner) GetAssignStateOk() (*RequestPostRequestInnerAssignState, bool) {
	if o == nil || IsNil(o.AssignState) {
		return nil, false
	}
	return o.AssignState, true
}

// HasAssignState returns a boolean if a field has been set.
func (o *RequestPostRequestInner) HasAssignState() bool {
	if o != nil && !IsNil(o.AssignState) {
		return true
	}

	return false
}

// SetAssignState gets a reference to the given RequestPostRequestInnerAssignState and assigns it to the AssignState field.
func (o *RequestPostRequestInner) SetAssignState(v RequestPostRequestInnerAssignState) {
	o.AssignState = &v
}

// GetDiscard returns the Discard field value if set, zero value otherwise.
func (o *RequestPostRequestInner) GetDiscard() bool {
	if o == nil || IsNil(o.Discard) {
		var ret bool
		return ret
	}
	return *o.Discard
}

// GetDiscardOk returns a tuple with the Discard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInner) GetDiscardOk() (*bool, bool) {
	if o == nil || IsNil(o.Discard) {
		return nil, false
	}
	return o.Discard, true
}

// HasDiscard returns a boolean if a field has been set.
func (o *RequestPostRequestInner) HasDiscard() bool {
	if o != nil && !IsNil(o.Discard) {
		return true
	}

	return false
}

// SetDiscard gets a reference to the given bool and assigns it to the Discard field.
func (o *RequestPostRequestInner) SetDiscard(v bool) {
	o.Discard = &v
}

// GetArgs returns the Args field value if set, zero value otherwise.
func (o *RequestPostRequestInner) GetArgs() RequestPostRequestInnerArgs {
	if o == nil || IsNil(o.Args) {
		var ret RequestPostRequestInnerArgs
		return ret
	}
	return *o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInner) GetArgsOk() (*RequestPostRequestInnerArgs, bool) {
	if o == nil || IsNil(o.Args) {
		return nil, false
	}
	return o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *RequestPostRequestInner) HasArgs() bool {
	if o != nil && !IsNil(o.Args) {
		return true
	}

	return false
}

// SetArgs gets a reference to the given RequestPostRequestInnerArgs and assigns it to the Args field.
func (o *RequestPostRequestInner) SetArgs(v RequestPostRequestInnerArgs) {
	o.Args = &v
}

// GetEnableSubstitution returns the EnableSubstitution field value if set, zero value otherwise.
func (o *RequestPostRequestInner) GetEnableSubstitution() bool {
	if o == nil || IsNil(o.EnableSubstitution) {
		var ret bool
		return ret
	}
	return *o.EnableSubstitution
}

// GetEnableSubstitutionOk returns a tuple with the EnableSubstitution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInner) GetEnableSubstitutionOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableSubstitution) {
		return nil, false
	}
	return o.EnableSubstitution, true
}

// HasEnableSubstitution returns a boolean if a field has been set.
func (o *RequestPostRequestInner) HasEnableSubstitution() bool {
	if o != nil && !IsNil(o.EnableSubstitution) {
		return true
	}

	return false
}

// SetEnableSubstitution gets a reference to the given bool and assigns it to the EnableSubstitution field.
func (o *RequestPostRequestInner) SetEnableSubstitution(v bool) {
	o.EnableSubstitution = &v
}

func (o RequestPostRequestInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestPostRequestInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AssignState) {
		toSerialize["assign_state"] = o.AssignState
	}
	if !IsNil(o.Discard) {
		toSerialize["discard"] = o.Discard
	}
	if !IsNil(o.Args) {
		toSerialize["args"] = o.Args
	}
	if !IsNil(o.EnableSubstitution) {
		toSerialize["enable_substitution"] = o.EnableSubstitution
	}
	return toSerialize, nil
}

type NullableRequestPostRequestInner struct {
	value *RequestPostRequestInner
	isSet bool
}

func (v NullableRequestPostRequestInner) Get() *RequestPostRequestInner {
	return v.value
}

func (v *NullableRequestPostRequestInner) Set(val *RequestPostRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestPostRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestPostRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestPostRequestInner(val *RequestPostRequestInner) *NullableRequestPostRequestInner {
	return &NullableRequestPostRequestInner{value: val, isSet: true}
}

func (v NullableRequestPostRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestPostRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


