/*
A record

creating docu of wapi a record documentation

API version: 2.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RequestPostRequestInnerAssignState type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestPostRequestInnerAssignState{}

// RequestPostRequestInnerAssignState State assignment for the response
type RequestPostRequestInnerAssignState struct {
	NetwRef *string `json:"netw_ref,omitempty"`
}

// NewRequestPostRequestInnerAssignState instantiates a new RequestPostRequestInnerAssignState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestPostRequestInnerAssignState() *RequestPostRequestInnerAssignState {
	this := RequestPostRequestInnerAssignState{}
	return &this
}

// NewRequestPostRequestInnerAssignStateWithDefaults instantiates a new RequestPostRequestInnerAssignState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestPostRequestInnerAssignStateWithDefaults() *RequestPostRequestInnerAssignState {
	this := RequestPostRequestInnerAssignState{}
	return &this
}

// GetNetwRef returns the NetwRef field value if set, zero value otherwise.
func (o *RequestPostRequestInnerAssignState) GetNetwRef() string {
	if o == nil || IsNil(o.NetwRef) {
		var ret string
		return ret
	}
	return *o.NetwRef
}

// GetNetwRefOk returns a tuple with the NetwRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInnerAssignState) GetNetwRefOk() (*string, bool) {
	if o == nil || IsNil(o.NetwRef) {
		return nil, false
	}
	return o.NetwRef, true
}

// HasNetwRef returns a boolean if a field has been set.
func (o *RequestPostRequestInnerAssignState) HasNetwRef() bool {
	if o != nil && !IsNil(o.NetwRef) {
		return true
	}

	return false
}

// SetNetwRef gets a reference to the given string and assigns it to the NetwRef field.
func (o *RequestPostRequestInnerAssignState) SetNetwRef(v string) {
	o.NetwRef = &v
}

func (o RequestPostRequestInnerAssignState) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestPostRequestInnerAssignState) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetwRef) {
		toSerialize["netw_ref"] = o.NetwRef
	}
	return toSerialize, nil
}

type NullableRequestPostRequestInnerAssignState struct {
	value *RequestPostRequestInnerAssignState
	isSet bool
}

func (v NullableRequestPostRequestInnerAssignState) Get() *RequestPostRequestInnerAssignState {
	return v.value
}

func (v *NullableRequestPostRequestInnerAssignState) Set(val *RequestPostRequestInnerAssignState) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestPostRequestInnerAssignState) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestPostRequestInnerAssignState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestPostRequestInnerAssignState(val *RequestPostRequestInnerAssignState) *NullableRequestPostRequestInnerAssignState {
	return &NullableRequestPostRequestInnerAssignState{value: val, isSet: true}
}

func (v NullableRequestPostRequestInnerAssignState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestPostRequestInnerAssignState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


