/*
A record

creating docu of wapi a record documentation

API version: 2.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RequestPostRequestInnerData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestPostRequestInnerData{}

// RequestPostRequestInnerData Data to be sent with the request (for GET requests)
type RequestPostRequestInnerData struct {
	Network *string `json:"network,omitempty"`
}

// NewRequestPostRequestInnerData instantiates a new RequestPostRequestInnerData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestPostRequestInnerData() *RequestPostRequestInnerData {
	this := RequestPostRequestInnerData{}
	return &this
}

// NewRequestPostRequestInnerDataWithDefaults instantiates a new RequestPostRequestInnerData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestPostRequestInnerDataWithDefaults() *RequestPostRequestInnerData {
	this := RequestPostRequestInnerData{}
	return &this
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *RequestPostRequestInnerData) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInnerData) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *RequestPostRequestInnerData) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *RequestPostRequestInnerData) SetNetwork(v string) {
	o.Network = &v
}

func (o RequestPostRequestInnerData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestPostRequestInnerData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	return toSerialize, nil
}

type NullableRequestPostRequestInnerData struct {
	value *RequestPostRequestInnerData
	isSet bool
}

func (v NullableRequestPostRequestInnerData) Get() *RequestPostRequestInnerData {
	return v.value
}

func (v *NullableRequestPostRequestInnerData) Set(val *RequestPostRequestInnerData) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestPostRequestInnerData) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestPostRequestInnerData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestPostRequestInnerData(val *RequestPostRequestInnerData) *NullableRequestPostRequestInnerData {
	return &NullableRequestPostRequestInnerData{value: val, isSet: true}
}

func (v NullableRequestPostRequestInnerData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestPostRequestInnerData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


