/*
A record

creating docu of wapi a record documentation

API version: 2.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RequestPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestPost200Response{}

// RequestPost200Response struct for RequestPost200Response
type RequestPost200Response struct {
	// Reference to the network object
	NetwRef *string `json:"netw_ref,omitempty"`
	// The next available IP address in the network
	NextAvailableIp *string `json:"next_available_ip,omitempty"`
}

// NewRequestPost200Response instantiates a new RequestPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestPost200Response() *RequestPost200Response {
	this := RequestPost200Response{}
	return &this
}

// NewRequestPost200ResponseWithDefaults instantiates a new RequestPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestPost200ResponseWithDefaults() *RequestPost200Response {
	this := RequestPost200Response{}
	return &this
}

// GetNetwRef returns the NetwRef field value if set, zero value otherwise.
func (o *RequestPost200Response) GetNetwRef() string {
	if o == nil || IsNil(o.NetwRef) {
		var ret string
		return ret
	}
	return *o.NetwRef
}

// GetNetwRefOk returns a tuple with the NetwRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPost200Response) GetNetwRefOk() (*string, bool) {
	if o == nil || IsNil(o.NetwRef) {
		return nil, false
	}
	return o.NetwRef, true
}

// HasNetwRef returns a boolean if a field has been set.
func (o *RequestPost200Response) HasNetwRef() bool {
	if o != nil && !IsNil(o.NetwRef) {
		return true
	}

	return false
}

// SetNetwRef gets a reference to the given string and assigns it to the NetwRef field.
func (o *RequestPost200Response) SetNetwRef(v string) {
	o.NetwRef = &v
}

// GetNextAvailableIp returns the NextAvailableIp field value if set, zero value otherwise.
func (o *RequestPost200Response) GetNextAvailableIp() string {
	if o == nil || IsNil(o.NextAvailableIp) {
		var ret string
		return ret
	}
	return *o.NextAvailableIp
}

// GetNextAvailableIpOk returns a tuple with the NextAvailableIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPost200Response) GetNextAvailableIpOk() (*string, bool) {
	if o == nil || IsNil(o.NextAvailableIp) {
		return nil, false
	}
	return o.NextAvailableIp, true
}

// HasNextAvailableIp returns a boolean if a field has been set.
func (o *RequestPost200Response) HasNextAvailableIp() bool {
	if o != nil && !IsNil(o.NextAvailableIp) {
		return true
	}

	return false
}

// SetNextAvailableIp gets a reference to the given string and assigns it to the NextAvailableIp field.
func (o *RequestPost200Response) SetNextAvailableIp(v string) {
	o.NextAvailableIp = &v
}

func (o RequestPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetwRef) {
		toSerialize["netw_ref"] = o.NetwRef
	}
	if !IsNil(o.NextAvailableIp) {
		toSerialize["next_available_ip"] = o.NextAvailableIp
	}
	return toSerialize, nil
}

type NullableRequestPost200Response struct {
	value *RequestPost200Response
	isSet bool
}

func (v NullableRequestPost200Response) Get() *RequestPost200Response {
	return v.value
}

func (v *NullableRequestPost200Response) Set(val *RequestPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestPost200Response(val *RequestPost200Response) *NullableRequestPost200Response {
	return &NullableRequestPost200Response{value: val, isSet: true}
}

func (v NullableRequestPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


