/*
A record

creating docu of wapi a record documentation

API version: 2.10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RequestPostRequestInnerArgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestPostRequestInnerArgs{}

// RequestPostRequestInnerArgs Arguments for the POST request
type RequestPostRequestInnerArgs struct {
	Function *string `json:"_function,omitempty"`
}

// NewRequestPostRequestInnerArgs instantiates a new RequestPostRequestInnerArgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestPostRequestInnerArgs() *RequestPostRequestInnerArgs {
	this := RequestPostRequestInnerArgs{}
	return &this
}

// NewRequestPostRequestInnerArgsWithDefaults instantiates a new RequestPostRequestInnerArgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestPostRequestInnerArgsWithDefaults() *RequestPostRequestInnerArgs {
	this := RequestPostRequestInnerArgs{}
	return &this
}

// GetFunction returns the Function field value if set, zero value otherwise.
func (o *RequestPostRequestInnerArgs) GetFunction() string {
	if o == nil || IsNil(o.Function) {
		var ret string
		return ret
	}
	return *o.Function
}

// GetFunctionOk returns a tuple with the Function field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestPostRequestInnerArgs) GetFunctionOk() (*string, bool) {
	if o == nil || IsNil(o.Function) {
		return nil, false
	}
	return o.Function, true
}

// HasFunction returns a boolean if a field has been set.
func (o *RequestPostRequestInnerArgs) HasFunction() bool {
	if o != nil && !IsNil(o.Function) {
		return true
	}

	return false
}

// SetFunction gets a reference to the given string and assigns it to the Function field.
func (o *RequestPostRequestInnerArgs) SetFunction(v string) {
	o.Function = &v
}

func (o RequestPostRequestInnerArgs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestPostRequestInnerArgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Function) {
		toSerialize["_function"] = o.Function
	}
	return toSerialize, nil
}

type NullableRequestPostRequestInnerArgs struct {
	value *RequestPostRequestInnerArgs
	isSet bool
}

func (v NullableRequestPostRequestInnerArgs) Get() *RequestPostRequestInnerArgs {
	return v.value
}

func (v *NullableRequestPostRequestInnerArgs) Set(val *RequestPostRequestInnerArgs) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestPostRequestInnerArgs) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestPostRequestInnerArgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestPostRequestInnerArgs(val *RequestPostRequestInnerArgs) *NullableRequestPostRequestInnerArgs {
	return &NullableRequestPostRequestInnerArgs{value: val, isSet: true}
}

func (v NullableRequestPostRequestInnerArgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestPostRequestInnerArgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


